-- 掲示板のスレッド
-- 作品のコメント（POSTテーブル）とは異なるので注意
CREATE TABLE THREADS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE TEXT,
    AUTHOR TEXT,
    CREATED_DATE INTEGER,
    LAST_COMMENT_DATE INTEGER
);

-- スレッドに紐づくコメント
CREATE TABLE COMMENTS(
    THREAD_ID INTEGER,
    SEQ INTEGER,
    COMMENTER TEXT,
    COMMENT TEXT,
    REPLY_TO INTEGER,
    COMMENT_DATE INTEGER,
    PRIMARY KEY(THREAD_ID,SEQ)
);