-- worksの履歴
CREATE TABLE HISTORY (
    ID INTEGER,
    SEQ INTEGER,
    BACKUP_DATE INTEGER NOT NULL,
    -- 以下はWORKSと同じ
    TESU INTEGER,
    TITLE TEXT,
    KIHU TEXT,
    EXPLANATION TEXT,
    AUTHOR TEXT,
    EDITOR TEXT,
    MAIN TEXT,
    TEGOMA TEXT,
    GOTETEGOMA TEXT,
    PUBLISH_DATE INTEGER,
    EDIT_DATE INTEGER,
    GOOD INTEGER,
    BAD INTEGER,
    DEMAND INTEGER,
    BACKUP_SEQ INTEGER
    COMMENT TEXT,
    PRIMARY KEY (ID,SEQ)
);