CREATE TABLE POSTS(
    -- WORKSのID
    ID INTEGER,
    SEQ INTEGER,
    NAME TEXT NOT NULL,
    COMMENT TEXT NOT NULL,
    -- GOOD,BAD,DEMAND
    TYPE TEXT NOT NULL,
    POST_DATE INTEGER NOT NULL,
    GOOD INTEGER NOT NULL,
    BAD INTEGER NOT NULL,
    PRIMARY KEY (ID,SEQ)
);